"""
ToPDF.py
========
A generic, automated Markdown & text-to-PDF converter using ReportLab.
Converts markdown reports, technical documentation, tables, and architectural specifications
into high-quality, beautifully styled publication-grade PDFs with custom headers, footers,
and two-pass page numbering ("Page X of Y").

Usage:
    CLI:
        python ToPDF.py input.md -o output.pdf [--title "Document Title"] [--author "Author"]
        python ToPDF.py --content "# Title\nSome content" -o output.pdf

    Python:
        from ToPDF import convert_markdown_to_pdf, convert_file_to_pdf
        convert_file_to_pdf("documentation.md", "documentation.pdf", title="My Report")
"""

import os
import sys
import re
import argparse
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

# ----------------------------------------------------------------------
# 1. TWO-PASS CANVAS WITH HEADERS, FOOTERS & PAGE NUMBERS
# ----------------------------------------------------------------------

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#718096"))
        page_width, page_height = self._pagesize

        # Running Header (pages > 1)
        if self._pageNumber > 1:
            header_text = getattr(self, 'doc_title', 'Technical Report')
            self.drawString(54, page_height - 36, header_text)
            self.setStrokeColor(colors.HexColor("#CBD5E0"))
            self.setLineWidth(0.5)
            self.line(54, page_height - 42, page_width - 54, page_height - 42)

        # Running Footer (all pages)
        footer_left = getattr(self, 'doc_footer', 'Generated by ToPDF')
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawString(54, 34, footer_left)
        self.drawRightString(page_width - 54, 34, page_str)
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 46, page_width - 54, 46)

        self.restoreState()


# ----------------------------------------------------------------------
# 2. COLOR PALETTE & TYPOGRAPHY STYLES
# ----------------------------------------------------------------------

def get_pdf_styles():
    styles = getSampleStyleSheet()

    # Custom Curated Colors
    PRIMARY = colors.HexColor("#1A365D")    # Deep Navy
    SECONDARY = colors.HexColor("#2B6CB0")  # Slate Blue
    DARK_TEXT = colors.HexColor("#2D3748")  # Charcoal
    LIGHT_BG = colors.HexColor("#F7FAFC")   # Soft Off-white
    ACCENT = colors.HexColor("#319795")     # Teal accent

    styles.add(ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=PRIMARY,
        spaceAfter=12,
        spaceBefore=0,
    ))

    styles.add(ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=SECONDARY,
        spaceAfter=18,
    ))

    styles.add(ParagraphStyle(
        'CustomH1',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=16,
        leading=20,
        textColor=PRIMARY,
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True
    ))

    styles.add(ParagraphStyle(
        'CustomH2',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=SECONDARY,
        spaceBefore=10,
        spaceAfter=5,
        keepWithNext=True
    ))

    styles.add(ParagraphStyle(
        'CustomH3',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=13,
        textColor=DARK_TEXT,
        spaceBefore=7,
        spaceAfter=3,
        keepWithNext=True
    ))

    styles.add(ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=DARK_TEXT,
        spaceAfter=6,
    ))

    styles.add(ParagraphStyle(
        'CustomBullet',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=DARK_TEXT,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=3,
    ))

    styles.add(ParagraphStyle(
        'Callout',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor("#2C5282"),
        spaceAfter=6,
    ))

    styles.add(ParagraphStyle(
        'CodeBlock',
        parent=styles['Normal'],
        fontName='Courier',
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor("#1A202C"),
        spaceAfter=6,
    ))

    styles.add(ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=10,
        textColor=colors.white,
        alignment=0
    ))

    styles.add(ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=7.5,
        leading=9.5,
        textColor=DARK_TEXT,
        alignment=0
    ))

    return styles


# ----------------------------------------------------------------------
# 3. MARKDOWN TO REPORTLAB FLOWABLES PARSER
# ----------------------------------------------------------------------

def escape_xml_text(text):
    """Safely escape text while preserving basic formatting tags"""
    # Replace & first
    text = text.replace('&', '&amp;')
    text = text.replace('<', '&lt;').replace('>', '&gt;')
    
    # Restore bold & italics from markdown
    # Convert `code` to <font name="Courier">code</font>
    text = re.sub(r'`([^`]+)`', r'<font name="Courier" color="#805AD5"><b>\1</b></font>', text)
    # Convert **bold** to <b>bold</b>
    text = re.sub(r'\*\*([^*]+)\*\*', r'<b>\1</b>', text)
    # Convert *italic* to <i>italic</i>
    text = re.sub(r'(?<!\*)\*([^*]+)\*(?!\*)', r'<i>\1</i>', text)
    
    # Re-allow basic tags
    text = text.replace('&lt;b&gt;', '<b>').replace('&lt;/b&gt;', '</b>')
    text = text.replace('&lt;i&gt;', '<i>').replace('&lt;/i&gt;', '</i>')
    text = text.replace('&lt;font', '<font').replace('&lt;/font&gt;', '</font>')
    text = text.replace('&quot;', '"')
    return text

def parse_markdown_to_flowables(md_text, styles, max_width=504):
    flowables = []
    lines = md_text.split('\n')
    i = 0
    n = len(lines)

    in_code_block = False
    code_lines = []

    while i < n:
        line = lines[i]
        raw_line = line.strip()

        # Handle Code Block
        if raw_line.startswith('```'):
            if in_code_block:
                # End of code block
                code_text = "<br/>".join([escape_xml_text(cl).replace(' ', '&nbsp;') for cl in code_lines])
                p = Paragraph(code_text, styles['CodeBlock'])
                t = Table([[p]], colWidths=[max_width])
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#EDF2F7")),
                    ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
                    ('TOPPADDING', (0, 0), (-1, -1), 6),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                    ('LEFTPADDING', (0, 0), (-1, -1), 8),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
                ]))
                flowables.append(t)
                flowables.append(Spacer(1, 4))
                in_code_block = False
                code_lines = []
            else:
                in_code_block = True
                code_lines = []
            i += 1
            continue

        if in_code_block:
            code_lines.append(line)
            i += 1
            continue

        # Blank Line
        if not raw_line:
            i += 1
            continue

        # Horizontal Rule
        if re.match(r'^(---+|\*\*\*+|___+)$', raw_line):
            flowables.append(HRFlowable(width="100%", thickness=0.75, color=colors.HexColor("#CBD5E0"), spaceBefore=6, spaceAfter=8))
            i += 1
            continue

        # Markdown Table Detection
        if raw_line.startswith('|') and raw_line.endswith('|'):
            table_lines = []
            while i < n and lines[i].strip().startswith('|') and lines[i].strip().endswith('|'):
                table_lines.append(lines[i].strip())
                i += 1

            if len(table_lines) >= 2:
                # Parse headers
                raw_headers = [c.strip() for c in table_lines[0].split('|')[1:-1]]
                num_cols = len(raw_headers)
                
                # Check for separator line (| :--- | :--- |)
                data_start_idx = 1
                if len(table_lines) > 1 and re.match(r'^[|\s:-]+$', table_lines[1]):
                    data_start_idx = 2

                table_data = []
                # Header row
                header_row = [Paragraph(escape_xml_text(h), styles['TableHeader']) for h in raw_headers]
                table_data.append(header_row)

                # Data rows
                for row_line in table_lines[data_start_idx:]:
                    cols = [c.strip() for c in row_line.split('|')[1:-1]]
                    # Pad or truncate to match num_cols
                    while len(cols) < num_cols:
                        cols.append('')
                    cols = cols[:num_cols]
                    data_row = [Paragraph(escape_xml_text(c), styles['TableCell']) for c in cols]
                    table_data.append(data_row)

                # Calculate balanced column widths
                col_width = max_width / num_cols
                col_widths = [col_width] * num_cols

                # Refine widths based on content lengths if possible
                if num_cols == 2:
                    col_widths = [max_width * 0.35, max_width * 0.65]
                elif num_cols == 3:
                    col_widths = [max_width * 0.25, max_width * 0.35, max_width * 0.40]
                elif num_cols == 4:
                    col_widths = [max_width * 0.20, max_width * 0.25, max_width * 0.25, max_width * 0.30]

                table = Table(table_data, colWidths=col_widths, repeatRows=1)
                t_style = [
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1A365D")),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
                    ('TOPPADDING', (0, 0), (-1, -1), 4),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                    ('LEFTPADDING', (0, 0), (-1, -1), 5),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 5),
                ]
                # Alternating row colors
                for r in range(1, len(table_data)):
                    bg = colors.HexColor("#F7FAFC") if r % 2 == 1 else colors.white
                    t_style.append(('BACKGROUND', (0, r), (-1, r), bg))

                table.setStyle(TableStyle(t_style))
                flowables.append(table)
                flowables.append(Spacer(1, 6))
            continue

        # Headings
        if raw_line.startswith('# '):
            flowables.append(Paragraph(escape_xml_text(raw_line[2:]), styles['DocTitle']))
            i += 1
            continue
        elif raw_line.startswith('## '):
            flowables.append(Paragraph(escape_xml_text(raw_line[3:]), styles['CustomH1']))
            i += 1
            continue
        elif raw_line.startswith('### '):
            flowables.append(Paragraph(escape_xml_text(raw_line[4:]), styles['CustomH2']))
            i += 1
            continue
        elif raw_line.startswith('#### '):
            flowables.append(Paragraph(escape_xml_text(raw_line[5:]), styles['CustomH3']))
            i += 1
            continue

        # Blockquote / Callout (> [!NOTE] or > text)
        if raw_line.startswith('>'):
            callout_text = raw_line[1:].strip()
            # If multiple blockquote lines exist, collect them
            bq_lines = [callout_text]
            while i + 1 < n and lines[i + 1].strip().startswith('>'):
                i += 1
                bq_lines.append(lines[i].strip()[1:].strip())
            
            combined_bq = " ".join(bq_lines)
            combined_bq = re.sub(r'^\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*', r'<b>[\1]</b> ', combined_bq)
            p = Paragraph(escape_xml_text(combined_bq), styles['Callout'])
            callout_box = Table([[p]], colWidths=[max_width])
            callout_box.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#EBF8FF")),
                ('LINELEFT', (0, 0), (-1, -1), 3.0, colors.HexColor("#2B6CB0")),
                ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#BEE3F8")),
                ('TOPPADDING', (0, 0), (-1, -1), 5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ]))
            flowables.append(callout_box)
            flowables.append(Spacer(1, 5))
            i += 1
            continue

        # Bullet List (- or *)
        if re.match(r'^[\*\-]\s+', raw_line):
            bullet_content = re.sub(r'^[\*\-]\s+', '', raw_line)
            p = Paragraph(f"&bull;&nbsp;&nbsp;{escape_xml_text(bullet_content)}", styles['CustomBullet'])
            flowables.append(p)
            i += 1
            continue

        # Numbered List (1. ...)
        m_num = re.match(r'^(\d+)\.\s+', raw_line)
        if m_num:
            num_str = m_num.group(1)
            num_content = raw_line[len(m_num.group(0)):]
            p = Paragraph(f"<b>{num_str}.</b>&nbsp;&nbsp;{escape_xml_text(num_content)}", styles['CustomBullet'])
            flowables.append(p)
            i += 1
            continue

        # Standard Body Paragraph
        flowables.append(Paragraph(escape_xml_text(raw_line), styles['CustomBody']))
        i += 1

    return flowables


# ----------------------------------------------------------------------
# 4. MAIN CONVERSION FUNCTIONS
# ----------------------------------------------------------------------

def convert_markdown_to_pdf(
    md_content: str,
    output_pdf_path: str,
    title: str = "Technical Specification",
    footer_text: str = "BlackSheep Engineering Architecture | Indian Railways",
    page_size=letter
):
    """
    Converts markdown content to a styled PDF file.
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_pdf_path)), exist_ok=True)
    
    doc = SimpleDocTemplate(
        output_pdf_path,
        pagesize=page_size,
        leftMargin=54,  # 0.75 in
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )

    page_width, page_height = page_size
    printable_width = page_width - 108

    styles = get_pdf_styles()
    flowables = parse_markdown_to_flowables(md_content, styles, max_width=printable_width)

    # Custom canvas maker carrying doc metadata
    def canvas_maker(*args, **kwargs):
        c = NumberedCanvas(*args, **kwargs)
        c.doc_title = title
        c.doc_footer = footer_text
        return c

    doc.build(flowables, canvasmaker=canvas_maker)
    print(f"[ToPDF] Successfully generated PDF: '{output_pdf_path}' ({os.path.getsize(output_pdf_path):,} bytes)")
    return output_pdf_path

def convert_file_to_pdf(
    input_file_path: str,
    output_pdf_path: str = None,
    title: str = None,
    footer_text: str = "BlackSheep Engineering Architecture | Indian Railways"
):
    """
    Reads markdown or text from input_file_path and produces output_pdf_path.
    """
    if not os.path.exists(input_file_path):
        raise FileNotFoundError(f"Input file not found: '{input_file_path}'")

    with open(input_file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    if output_pdf_path is None:
        base, _ = os.path.splitext(input_file_path)
        output_pdf_path = base + ".pdf"

    if title is None:
        # Infer title from first H1 if available
        for line in content.split('\n'):
            line = line.strip()
            if line.startswith('# '):
                title = line[2:].strip()
                break
        if not title:
            title = os.path.splitext(os.path.basename(input_file_path))[0].replace('_', ' ').title()

    return convert_markdown_to_pdf(content, output_pdf_path, title=title, footer_text=footer_text)


# ----------------------------------------------------------------------
# 5. CLI INTERFACE
# ----------------------------------------------------------------------

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="ToPDF: Generic Markdown/Document to PDF Converter")
    parser.add_argument('input_file', nargs='?', help="Path to input Markdown or text file")
    parser.add_argument('-o', '--output', help="Output PDF file path (default: <input_basename>.pdf)")
    parser.add_argument('--title', help="Document title for header")
    parser.add_argument('--footer', default="BlackSheep Engineering Architecture | Indian Railways", help="Footer text")
    parser.add_argument('--content', help="Raw markdown string to convert directly")

    args = parser.parse_args()

    if args.content:
        out = args.output or "output.pdf"
        t = args.title or "Document"
        convert_markdown_to_pdf(args.content, out, title=t, footer_text=args.footer)
    elif args.input_file:
        convert_file_to_pdf(args.input_file, args.output, title=args.title, footer_text=args.footer)
    else:
        parser.print_help()
